# SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and Operational Context Graph contributors
#
# SPDX-License-Identifier: Apache-2.0
apiVersion: v2
name: data-ingestion
description: Data Ingestion service
type: application
version: 0.1.0
appVersion: "0.1.0"
