# SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and Operational Context Graph contributors
#
# SPDX-License-Identifier: Apache-2.0
---
name: Buf

on:
  push:
    paths:
      - 'proto/**'
      - 'buf.yaml'
      - 'buf.gen.yaml'
      - '.github/workflows/buf.yaml'
  pull_request:
    paths:
      - 'proto/**'
      - 'buf.yaml'
      - 'buf.gen.yaml'
      - '.github/workflows/buf.yaml'

permissions:
  contents: read

jobs:
  buf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Buf
        uses: bufbuild/buf-action@85aebf73123b5c15fd5528aaecbf9129cddf7fa7 # v1.6.0
        with:
          lint: true
          format: true
          breaking: true
